# Importing Libraries

In [2]:
from googleapiclient.discovery import build
import pandas as pd
import os
from dotenv import load_dotenv

# YouTube Connection

In [4]:
load_dotenv()

api_key = os.getenv('API_KEY')

youtube = build('youtube', 'v3', developerKey=api_key)

# Data Science Channel IDs

In [5]:
channel_ids = ['UCEBpSZhI1X8WaP-kY_2LLcg',
               'UCiT9RITQ9PW6BhXK0y2jaeg',
               'UCzL_0nIe8B4-7ShhVPfJkgw',
               'UC79Gv3mYp6zKiSwYemEik9A',
               'UCV8e2g4IWQqK71bbzGDEI4Q',
               'UCtYLUTtgS3k1Fg4y5tAhLbw',
               'UC7cs8q-gJRlGwj4A8OmCmXg',
               'UCiT9RITQ9PW6BhXK0y2jaeg',
               'UCnz-ZXXER4jOvuED5trXfEA',
               'UCteRPiisgIoHtMgqHegpWAQ',
               'UCSMqVwPTmerMiCaL_zKRjBw',
               'UCJublDh2UsiIKsAE1553miw',
               'UCvZnwzmc3m1Eush-Or8Z6DA',
               'UCNU_lfiiWBdtULKOw6X0Dig',
               'UCRqCK8izkO5xeVVtMKSHeRQ',
               'UC9LfrPNcIyHspci0t2W4T_w',
               'UCJQJAI7IjbLcpsjWdSzYz0Q',
               'UCaGe6wVIAymH17HKO8kjQsw',
               'UCWzIuRTyadYzg1-6OCejRMg',
               'UCHXa4OpASJEwrHrLeIzw7Yg',
               'UCb5aI-GwJm3ZxlwtCsLu78Q',
               'UCHGw1uT1XmqaRm-6W15-KlQ',
               'UCmMGlb7mGXYVthrXYSwlQhw',
               'UCSATlCAUi7R0Ik-wsZb2gOA',
               'UCDybamfye5An6p-j1t2YMsg',
               'UCVhQ2NnY5Rskt6UjCUkJ_DA',
               'UCq6XkhO5SZ66N04IcPbqNcw',
               'UCn1O_4_ApzbYwrsUdRoMmOg',
               'UCUIBKDoSSwehuDK4jk1CjFQ',
               'UCw_LFe2pS8x3NyipGNJgeEA',
               'UCPvDKIsrjA_h3g5yZJwCIHA',
               'UCObs0kLIrDjX2LLSybqNaEA',
               'UCChmJrVa8kDg05JfCmxpLRw',
               'UCup-fnSNRaByeuXOWqfnykw',
               'UCI8JpGrDmtggrryhml8kFGw',
               'UCkRFwipiIqBTakN-mkZ-GcQ']

# Function to Gather Channel Stats

In [6]:
def get_channel_stats(youtube, channel_id):
    
    all_data = []
    
    request = youtube.channels().list(part='snippet,contentDetails,statistics', id=','.join(channel_ids))
    
    response = request.execute()
    
    for i in range(len(response['items'])):
        data = dict(channel_name = response['items'][i]['snippet']['title'],
                channel_id = response['items'][i]['id'],
                subscribers = response['items'][i]['statistics']['subscriberCount'],
                total_views = response['items'][i]['statistics']['viewCount'],
                total_videos = response['items'][i]['statistics']['videoCount'],
                playlist_id = response['items'][i]['contentDetails']['relatedPlaylists']['uploads'])
        all_data.append(data)
    
    return all_data

In [7]:
channel_stats = get_channel_stats(youtube, channel_ids)

In [8]:
request = youtube.channels().list(part='snippet,contentDetails,statistics', forUsername='TinaHueng1')
response = request.execute()
response

{'kind': 'youtube#channelListResponse',
 'etag': 'RuuXzTIr0OoDqI4S0RU6n4FqKEM',
 'pageInfo': {'totalResults': 0, 'resultsPerPage': 5}}

# Creating Dataframe

In [9]:
channel_stats_df = pd.DataFrame(channel_stats)
channel_stats_df

,channel_name,channel_id,subscribers,total_views,total_videos,playlist_id
0,Data36 - Online Data Science Courses,UC9LfrPNcIyHspci0t2W4T_w,4810,205079,69,UU9LfrPNcIyHspci0t2W4T_w
1,Ayush Singh,UCkRFwipiIqBTakN-mkZ-GcQ,63500,1824000,22,UUkRFwipiIqBTakN-mkZ-GcQ
2,Andy McDonald,UCn1O_4_ApzbYwrsUdRoMmOg,6550,296750,48,UUn1O_4_ApzbYwrsUdRoMmOg
3,Data Science Dojo,UCzL_0nIe8B4-7ShhVPfJkgw,101000,5716024,455,UUzL_0nIe8B4-7ShhVPfJkgw
4,Darshil Parmar,UCChmJrVa8kDg05JfCmxpLRw,103000,4276918,138,UUChmJrVa8kDg05JfCmxpLRw
5,Time Out With Tim,UCSATlCAUi7R0Ik-wsZb2gOA,6410,28458,9,UUSATlCAUi7R0Ik-wsZb2gOA
6,Jon Krohn,UCup-fnSNRaByeuXOWqfnykw,18700,710692,143,UUup-fnSNRaByeuXOWqfnykw
7,techTFQ,UCnz-ZXXER4jOvuED5trXfEA,253000,13273096,100,UUnz-ZXXER4jOvuED5trXfEA
8,StatQuest with Josh Starmer,UCtYLUTtgS3k1Fg4y5tAhLbw,1050000,56817108,265,UUtYLUTtgS3k1Fg4y5tAhLbw
9,Data Nash,UCRqCK8izkO5xeVVtMKSHeRQ,18800,898892,50,UURqCK8izkO5xeVVtMKSHeRQ
10,Data Science Basics,UCHGw1uT1XmqaRm-6W15-KlQ,5850,294041,149,UUHGw1uT1XmqaRm-6W15-KlQ
11,Shashank Kalanithi,UCvZnwzmc3m1Eush-Or8Z6DA,139000,6517931,152,UUvZnwzmc3m1Eush-Or8Z6DA
12,Learn with Lukas,UCw_LFe2pS8x3NyipGNJgeEA,28000,1503407,55,UUw_LFe2pS8x3NyipGNJgeEA
13,365 Data Science,UCEBpSZhI1X8WaP-kY_2LLcg,302000,13369923,223,UUEBpSZhI1X8WaP-kY_2LLcg
14,Dataiku,UCSMqVwPTmerMiCaL_zKRjBw,15200,9131105,684,UUSMqVwPTmerMiCaL_zKRjBw
15,Data With Mo,UCDybamfye5An6p-j1t2YMsg,73500,2209969,66,UUDybamfye5An6p-j1t2YMsg
16,Tech Classes,UCPvDKIsrjA_h3g5yZJwCIHA,29600,1915382,155,UUPvDKIsrjA_h3g5yZJwCIHA
17,Sundas Khalid,UCteRPiisgIoHtMgqHegpWAQ,182000,9187073,115,UUteRPiisgIoHtMgqHegpWAQ
18,Great Learning,UCObs0kLIrDjX2LLSybqNaEA,808000,62906584,1854,UUObs0kLIrDjX2LLSybqNaEA
19,luke barousse,UCaGe6wVIAymH17HKO8kjQsw,369,4390,9,UUaGe6wVIAymH17HKO8kjQsw
20,DataCamp,UC79Gv3mYp6zKiSwYemEik9A,154000,22774820,1521,UU79Gv3mYp6zKiSwYemEik9A
21,Data Science for High School,UCWzIuRTyadYzg1-6OCejRMg,32,1327,34,UUWzIuRTyadYzg1-6OCejRMg
22,Tom Henry - data science with R,UCb5aI-GwJm3ZxlwtCsLu78Q,3760,191890,16,UUb5aI-GwJm3ZxlwtCsLu78Q
23,Joma in NYC,UCmMGlb7mGXYVthrXYSwlQhw,260000,14905547,20,UUmMGlb7mGXYVthrXYSwlQhw
24,Thu Vu data analytics,UCJQJAI7IjbLcpsjWdSzYz0Q,176000,5873792,79,UUJQJAI7IjbLcpsjWdSzYz0Q
25,Krish Naik,UCNU_lfiiWBdtULKOw6X0Dig,844000,85477519,1749,UUNU_lfiiWBdtULKOw6X0Dig
26,Data Professor,UCV8e2g4IWQqK71bbzGDEI4Q,169000,5429760,324,UUV8e2g4IWQqK71bbzGDEI4Q
27,Ken Jee,UCiT9RITQ9PW6BhXK0y2jaeg,254000,8718474,286,UUiT9RITQ9PW6BhXK0y2jaeg
28,Nicholas Renotte,UCHXa4OpASJEwrHrLeIzw7Yg,217000,13920090,303,UUHXa4OpASJEwrHrLeIzw7Yg
29,Greg Hogg,UCJublDh2UsiIKsAE1553miw,56700,3548012,551,UUJublDh2UsiIKsAE1553miw
30,Alex The Analyst,UC7cs8q-gJRlGwj4A8OmCmXg,637000,27009713,265,UU7cs8q-gJRlGwj4A8OmCmXg
31,ArjanCodes,UCVhQ2NnY5Rskt6UjCUkJ_DA,208000,14230141,306,UUVhQ2NnY5Rskt6UjCUkJ_DA
32,Study with Tina,UCI8JpGrDmtggrryhml8kFGw,20900,290825,249,UUI8JpGrDmtggrryhml8kFGw
33,Keith Galli,UCq6XkhO5SZ66N04IcPbqNcw,208000,14248278,80,UUq6XkhO5SZ66N04IcPbqNcw
34,Rocketing Data Science,UCUIBKDoSSwehuDK4jk1CjFQ,1800,160991,88,UUUIBKDoSSwehuDK4jk1CjFQ

In [10]:
channel_stats_df.dtypes

channel_name    object
channel_id      object
subscribers     object
total_views     object
total_videos    object
playlist_id     object
dtype: object

In [11]:
channel_stats_df[['subscribers', 'total_views', 'total_videos']] = channel_stats_df[['subscribers', 'total_views', 'total_videos']].astype(int)

# Choosing Channels Based on Size

In [12]:
channel_stats_df.describe().round(2)

       subscribers  total_views  total_videos
count        35.00        35.00         35.00
mean     183413.74  11653371.46        303.77
std      259487.13  19245337.00        465.10
min          32.00      1327.00          9.00
25%       16950.00    503721.00         60.50
50%      101000.00   5429760.00        143.00
75%      212500.00  13645006.50        294.50
max     1050000.00  85477519.00       1854.00

In [13]:
channel_stats_df.sort_values('subscribers', ascending=False)

,channel_name,channel_id,subscribers,total_views,total_videos,playlist_id
8,StatQuest with Josh Starmer,UCtYLUTtgS3k1Fg4y5tAhLbw,1050000,56817108,265,UUtYLUTtgS3k1Fg4y5tAhLbw
25,Krish Naik,UCNU_lfiiWBdtULKOw6X0Dig,844000,85477519,1749,UUNU_lfiiWBdtULKOw6X0Dig
18,Great Learning,UCObs0kLIrDjX2LLSybqNaEA,808000,62906584,1854,UUObs0kLIrDjX2LLSybqNaEA
30,Alex The Analyst,UC7cs8q-gJRlGwj4A8OmCmXg,637000,27009713,265,UU7cs8q-gJRlGwj4A8OmCmXg
13,365 Data Science,UCEBpSZhI1X8WaP-kY_2LLcg,302000,13369923,223,UUEBpSZhI1X8WaP-kY_2LLcg
23,Joma in NYC,UCmMGlb7mGXYVthrXYSwlQhw,260000,14905547,20,UUmMGlb7mGXYVthrXYSwlQhw
27,Ken Jee,UCiT9RITQ9PW6BhXK0y2jaeg,254000,8718474,286,UUiT9RITQ9PW6BhXK0y2jaeg
7,techTFQ,UCnz-ZXXER4jOvuED5trXfEA,253000,13273096,100,UUnz-ZXXER4jOvuED5trXfEA
28,Nicholas Renotte,UCHXa4OpASJEwrHrLeIzw7Yg,217000,13920090,303,UUHXa4OpASJEwrHrLeIzw7Yg
31,ArjanCodes,UCVhQ2NnY5Rskt6UjCUkJ_DA,208000,14230141,306,UUVhQ2NnY5Rskt6UjCUkJ_DA
33,Keith Galli,UCq6XkhO5SZ66N04IcPbqNcw,208000,14248278,80,UUq6XkhO5SZ66N04IcPbqNcw
17,Sundas Khalid,UCteRPiisgIoHtMgqHegpWAQ,182000,9187073,115,UUteRPiisgIoHtMgqHegpWAQ
24,Thu Vu data analytics,UCJQJAI7IjbLcpsjWdSzYz0Q,176000,5873792,79,UUJQJAI7IjbLcpsjWdSzYz0Q
26,Data Professor,UCV8e2g4IWQqK71bbzGDEI4Q,169000,5429760,324,UUV8e2g4IWQqK71bbzGDEI4Q
20,DataCamp,UC79Gv3mYp6zKiSwYemEik9A,154000,22774820,1521,UU79Gv3mYp6zKiSwYemEik9A
11,Shashank Kalanithi,UCvZnwzmc3m1Eush-Or8Z6DA,139000,6517931,152,UUvZnwzmc3m1Eush-Or8Z6DA
4,Darshil Parmar,UCChmJrVa8kDg05JfCmxpLRw,103000,4276918,138,UUChmJrVa8kDg05JfCmxpLRw
3,Data Science Dojo,UCzL_0nIe8B4-7ShhVPfJkgw,101000,5716024,455,UUzL_0nIe8B4-7ShhVPfJkgw
15,Data With Mo,UCDybamfye5An6p-j1t2YMsg,73500,2209969,66,UUDybamfye5An6p-j1t2YMsg
1,Ayush Singh,UCkRFwipiIqBTakN-mkZ-GcQ,63500,1824000,22,UUkRFwipiIqBTakN-mkZ-GcQ
29,Greg Hogg,UCJublDh2UsiIKsAE1553miw,56700,3548012,551,UUJublDh2UsiIKsAE1553miw
16,Tech Classes,UCPvDKIsrjA_h3g5yZJwCIHA,29600,1915382,155,UUPvDKIsrjA_h3g5yZJwCIHA
12,Learn with Lukas,UCw_LFe2pS8x3NyipGNJgeEA,28000,1503407,55,UUw_LFe2pS8x3NyipGNJgeEA
32,Study with Tina,UCI8JpGrDmtggrryhml8kFGw,20900,290825,249,UUI8JpGrDmtggrryhml8kFGw
9,Data Nash,UCRqCK8izkO5xeVVtMKSHeRQ,18800,898892,50,UURqCK8izkO5xeVVtMKSHeRQ
6,Jon Krohn,UCup-fnSNRaByeuXOWqfnykw,18700,710692,143,UUup-fnSNRaByeuXOWqfnykw
14,Dataiku,UCSMqVwPTmerMiCaL_zKRjBw,15200,9131105,684,UUSMqVwPTmerMiCaL_zKRjBw
2,Andy McDonald,UCn1O_4_ApzbYwrsUdRoMmOg,6550,296750,48,UUn1O_4_ApzbYwrsUdRoMmOg
5,Time Out With Tim,UCSATlCAUi7R0Ik-wsZb2gOA,6410,28458,9,UUSATlCAUi7R0Ik-wsZb2gOA
10,Data Science Basics,UCHGw1uT1XmqaRm-6W15-KlQ,5850,294041,149,UUHGw1uT1XmqaRm-6W15-KlQ
0,Data36 - Online Data Science Courses,UC9LfrPNcIyHspci0t2W4T_w,4810,205079,69,UU9LfrPNcIyHspci0t2W4T_w
22,Tom Henry - data science with R,UCb5aI-GwJm3ZxlwtCsLu78Q,3760,191890,16,UUb5aI-GwJm3ZxlwtCsLu78Q
34,Rocketing Data Science,UCUIBKDoSSwehuDK4jk1CjFQ,1800,160991,88,UUUIBKDoSSwehuDK4jk1CjFQ
19,luke barousse,UCaGe6wVIAymH17HKO8kjQsw,369,4390,9,UUaGe6wVIAymH17HKO8kjQsw
21,Data Science for High School,UCWzIuRTyadYzg1-6OCejRMg,32,1327,34,UUWzIuRTyadYzg1-6OCejRMg

#### Only channels with over 20,000 subscribers and over 50 total videos

In [14]:
chosen_channels_df = channel_stats_df[(channel_stats_df.subscribers >= 20000) & (channel_stats_df.total_videos >= 50)].reset_index(drop=True)

In [15]:
chosen_channels_df

,channel_name,channel_id,subscribers,total_views,total_videos,playlist_id
0,Data Science Dojo,UCzL_0nIe8B4-7ShhVPfJkgw,101000,5716024,455,UUzL_0nIe8B4-7ShhVPfJkgw
1,Darshil Parmar,UCChmJrVa8kDg05JfCmxpLRw,103000,4276918,138,UUChmJrVa8kDg05JfCmxpLRw
2,techTFQ,UCnz-ZXXER4jOvuED5trXfEA,253000,13273096,100,UUnz-ZXXER4jOvuED5trXfEA
3,StatQuest with Josh Starmer,UCtYLUTtgS3k1Fg4y5tAhLbw,1050000,56817108,265,UUtYLUTtgS3k1Fg4y5tAhLbw
4,Shashank Kalanithi,UCvZnwzmc3m1Eush-Or8Z6DA,139000,6517931,152,UUvZnwzmc3m1Eush-Or8Z6DA
5,Learn with Lukas,UCw_LFe2pS8x3NyipGNJgeEA,28000,1503407,55,UUw_LFe2pS8x3NyipGNJgeEA
6,365 Data Science,UCEBpSZhI1X8WaP-kY_2LLcg,302000,13369923,223,UUEBpSZhI1X8WaP-kY_2LLcg
7,Data With Mo,UCDybamfye5An6p-j1t2YMsg,73500,2209969,66,UUDybamfye5An6p-j1t2YMsg
8,Tech Classes,UCPvDKIsrjA_h3g5yZJwCIHA,29600,1915382,155,UUPvDKIsrjA_h3g5yZJwCIHA
9,Sundas Khalid,UCteRPiisgIoHtMgqHegpWAQ,182000,9187073,115,UUteRPiisgIoHtMgqHegpWAQ
10,Great Learning,UCObs0kLIrDjX2LLSybqNaEA,808000,62906584,1854,UUObs0kLIrDjX2LLSybqNaEA
11,DataCamp,UC79Gv3mYp6zKiSwYemEik9A,154000,22774820,1521,UU79Gv3mYp6zKiSwYemEik9A
12,Thu Vu data analytics,UCJQJAI7IjbLcpsjWdSzYz0Q,176000,5873792,79,UUJQJAI7IjbLcpsjWdSzYz0Q
13,Krish Naik,UCNU_lfiiWBdtULKOw6X0Dig,844000,85477519,1749,UUNU_lfiiWBdtULKOw6X0Dig
14,Data Professor,UCV8e2g4IWQqK71bbzGDEI4Q,169000,5429760,324,UUV8e2g4IWQqK71bbzGDEI4Q
15,Ken Jee,UCiT9RITQ9PW6BhXK0y2jaeg,254000,8718474,286,UUiT9RITQ9PW6BhXK0y2jaeg
16,Nicholas Renotte,UCHXa4OpASJEwrHrLeIzw7Yg,217000,13920090,303,UUHXa4OpASJEwrHrLeIzw7Yg
17,Greg Hogg,UCJublDh2UsiIKsAE1553miw,56700,3548012,551,UUJublDh2UsiIKsAE1553miw
18,Alex The Analyst,UC7cs8q-gJRlGwj4A8OmCmXg,637000,27009713,265,UU7cs8q-gJRlGwj4A8OmCmXg
19,ArjanCodes,UCVhQ2NnY5Rskt6UjCUkJ_DA,208000,14230141,306,UUVhQ2NnY5Rskt6UjCUkJ_DA
20,Study with Tina,UCI8JpGrDmtggrryhml8kFGw,20900,290825,249,UUI8JpGrDmtggrryhml8kFGw
21,Keith Galli,UCq6XkhO5SZ66N04IcPbqNcw,208000,14248278,80,UUq6XkhO5SZ66N04IcPbqNcw

# Getting Base Video ID List

In [16]:
playlist_ids = chosen_channels_df['playlist_id']

In [17]:
def mass_video_ids(youtube, wanted_playlist_ids):

    all_data = []

    for id in wanted_playlist_ids:
        
        nextpage = True
        page = None

        while nextpage:
        # request for first page of playlist
            request = youtube.playlistItems().list(
                part='contentDetails',
                playlistId = id,
                maxResults=50,
                pageToken=page)
            # dictionary of the first page   
            response = request.execute()

        # Accessing videos ids on that first page
            for i in range(len(response['items'])):
                data = dict(playlist_id = id,
                    video_id = response['items'][i]['contentDetails']['videoId'])
                all_data.append(data)

            # Checking to see if there is a next page
            if 'nextPageToken' in response:
                page = response['nextPageToken']              

            else:
                nextpage = False
    # 
    all_data_df = pd.DataFrame(all_data)

    return all_data_df

In [25]:
video_ids_df = mass_video_ids(youtube, playlist_ids)

In [26]:
video_ids_df.head()

                playlist_id     video_id
0  UUzL_0nIe8B4-7ShhVPfJkgw  Zuh-VwgP2Bk
1  UUzL_0nIe8B4-7ShhVPfJkgw  N-Pj81XJyHw
2  UUzL_0nIe8B4-7ShhVPfJkgw  qDtif1zxbkY
3  UUzL_0nIe8B4-7ShhVPfJkgw  NuCb3ZHUA6Q
4  UUzL_0nIe8B4-7ShhVPfJkgw  lXIedWJRqd4

In [27]:
video_ids_df.shape

(9251, 2)

In [39]:
base_video_id_list = list(video_ids_df['video_id'])
len(base_video_id_list)

9251

In [ ]:
base_playlist_ids_list = list(playlist_ids)
base_playlist_ids_list

In [34]:
import pickle

In [46]:
with open('grab_list.pkl', 'wb') as file:
    pickle.dump([], file)

In [44]:
with open('base_video_id_list.pkl', 'wb') as file:
    pickle.dump(base_video_id_list, file)

In [45]:
with open('chosen_playlist_ids.pkl', 'wb') as file:
    pickle.dump(base_playlist_ids_list, file)

# Setting up for Day Zero

In [ ]:
columns = ['video_id', 'channel_id', 'published_at', 'title', 'description', 'tags', 'category_id', 'duration', 'caption',
         'licensed_content', 'default_language', 'content_rating', 'view_count', 'like_count', 'favourite_count', 'comment_count']

In [ ]:
dynamic_df = pd.DataFrame(columns=columns)

In [ ]:
def save_dynamic_df(df):
    with open('dynamic_df.pkl', 'wb') as file:
        pickle.dump(df, file)

In [ ]:
save_dynamic_df(dynamic_df)