# Importing Libraries

In [2]:
from googleapiclient.discovery import build
import pandas as pd
import seaborn as sns

# API Key

In [3]:
# api key AIzaSyBAobEQD70yA3gEWGjeZxGfyvvlwvMDsr8

# Configuring YouTube Connection

In [4]:
api_key = 'AIzaSyBAobEQD70yA3gEWGjeZxGfyvvlwvMDsr8'

youtube = build('youtube', 'v3', developerKey=api_key)

# List of Wanted Channel's IDs

In [5]:
channel_ids = ['UCEBpSZhI1X8WaP-kY_2LLcg',
               'UCiT9RITQ9PW6BhXK0y2jaeg',
               'UCzL_0nIe8B4-7ShhVPfJkgw',
               'UC79Gv3mYp6zKiSwYemEik9A',
               'UCV8e2g4IWQqK71bbzGDEI4Q',
               'UCtYLUTtgS3k1Fg4y5tAhLbw',
               'UC7cs8q-gJRlGwj4A8OmCmXg',
               'UCiT9RITQ9PW6BhXK0y2jaeg',
               'UCnz-ZXXER4jOvuED5trXfEA',
               'UCteRPiisgIoHtMgqHegpWAQ',
               'UCSMqVwPTmerMiCaL_zKRjBw',
               'UCJublDh2UsiIKsAE1553miw',
               'UCvZnwzmc3m1Eush-Or8Z6DA',
               'UCNU_lfiiWBdtULKOw6X0Dig',
               'UCRqCK8izkO5xeVVtMKSHeRQ',
               'UC9LfrPNcIyHspci0t2W4T_w',
               'UCJQJAI7IjbLcpsjWdSzYz0Q',
               'UCaGe6wVIAymH17HKO8kjQsw',
               'UCWzIuRTyadYzg1-6OCejRMg',
               'UCHXa4OpASJEwrHrLeIzw7Yg',
               'UCb5aI-GwJm3ZxlwtCsLu78Q',
               'UCHGw1uT1XmqaRm-6W15-KlQ',
               'UCmMGlb7mGXYVthrXYSwlQhw',
               'UCQALLeQPoZdZC4JNUboVEUg',
               'UCSATlCAUi7R0Ik-wsZb2gOA',
               'UC1emV4A8liRs9p80CY8ElUQ',
               'UCDybamfye5An6p-j1t2YMsg',
               'UCVhQ2NnY5Rskt6UjCUkJ_DA',
               'UCq6XkhO5SZ66N04IcPbqNcw',
               'UCn1O_4_ApzbYwrsUdRoMmOg',
               'UCUIBKDoSSwehuDK4jk1CjFQ',
               'UCw_LFe2pS8x3NyipGNJgeEA',
               'UCPvDKIsrjA_h3g5yZJwCIHA',
               'UCObs0kLIrDjX2LLSybqNaEA',
               'UCChmJrVa8kDg05JfCmxpLRw',
               'UCup-fnSNRaByeuXOWqfnykw',
               'UCI8JpGrDmtggrryhml8kFGw']

# Function to Gather Channel Information

In [6]:
def get_channel_stats(youtube, channel_id):
    
    all_data = []
    
    request = youtube.channels().list(part='snippet,contentDetails,statistics', id=','.join(channel_ids))
    
    response = request.execute()
    
    for i in range(len(response['items'])):
        data = dict(channel_name = response['items'][i]['snippet']['title'],
                channel_id = response['items'][i]['id'],
                subscribers = response['items'][i]['statistics']['subscriberCount'],
                total_views = response['items'][i]['statistics']['viewCount'],
                total_videos = response['items'][i]['statistics']['videoCount'],
                playlist_id = response['items'][i]['contentDetails']['relatedPlaylists']['uploads'])
        all_data.append(data)
    
    return all_data

In [7]:
channel_stats = get_channel_stats(youtube, channel_ids)

# Channel Stats Dataframe

In [8]:
channel_stats_df = pd.DataFrame(channel_stats)
channel_stats_df

,channel_name,channel_id,subscribers,total_views,total_videos,playlist_id
0,freeCodeCamp Espa√±ol,UC1emV4A8liRs9p80CY8ElUQ,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ
1,Data Science Dojo,UCzL_0nIe8B4-7ShhVPfJkgw,101000,5703952,454,UUzL_0nIe8B4-7ShhVPfJkgw
2,Shashank Kalanithi,UCvZnwzmc3m1Eush-Or8Z6DA,138000,6496719,152,UUvZnwzmc3m1Eush-Or8Z6DA
3,Study with Tina,UCI8JpGrDmtggrryhml8kFGw,20900,290543,249,UUI8JpGrDmtggrryhml8kFGw
4,Data Science for High School,UCWzIuRTyadYzg1-6OCejRMg,32,1312,34,UUWzIuRTyadYzg1-6OCejRMg
5,Time Out With Tim,UCSATlCAUi7R0Ik-wsZb2gOA,6410,28437,9,UUSATlCAUi7R0Ik-wsZb2gOA
6,StatQuest with Josh Starmer,UCtYLUTtgS3k1Fg4y5tAhLbw,1040000,56462115,265,UUtYLUTtgS3k1Fg4y5tAhLbw
7,Great Learning,UCObs0kLIrDjX2LLSybqNaEA,807000,62821553,1853,UUObs0kLIrDjX2LLSybqNaEA
8,Data Science Basics,UCHGw1uT1XmqaRm-6W15-KlQ,5690,286334,146,UUHGw1uT1XmqaRm-6W15-KlQ
9,Jon Krohn,UCup-fnSNRaByeuXOWqfnykw,18400,700682,143,UUup-fnSNRaByeuXOWqfnykw
10,Ken Jee,UCiT9RITQ9PW6BhXK0y2jaeg,254000,8706690,285,UUiT9RITQ9PW6BhXK0y2jaeg
11,Keith Galli,UCq6XkhO5SZ66N04IcPbqNcw,208000,14211727,79,UUq6XkhO5SZ66N04IcPbqNcw
12,Dataiku,UCSMqVwPTmerMiCaL_zKRjBw,15100,9123540,675,UUSMqVwPTmerMiCaL_zKRjBw
13,365 Data Science,UCEBpSZhI1X8WaP-kY_2LLcg,301000,13336869,223,UUEBpSZhI1X8WaP-kY_2LLcg
14,Tech Classes,UCPvDKIsrjA_h3g5yZJwCIHA,29400,1896823,155,UUPvDKIsrjA_h3g5yZJwCIHA
15,Joma in NYC,UCmMGlb7mGXYVthrXYSwlQhw,260000,14896170,20,UUmMGlb7mGXYVthrXYSwlQhw
16,Nicholas Renotte,UCHXa4OpASJEwrHrLeIzw7Yg,215000,13780735,303,UUHXa4OpASJEwrHrLeIzw7Yg
17,Sundas Khalid,UCteRPiisgIoHtMgqHegpWAQ,181000,9095601,114,UUteRPiisgIoHtMgqHegpWAQ
18,ArjanCodes,UCVhQ2NnY5Rskt6UjCUkJ_DA,206000,14048082,305,UUVhQ2NnY5Rskt6UjCUkJ_DA
19,Data Nash,UCRqCK8izkO5xeVVtMKSHeRQ,18500,888903,50,UURqCK8izkO5xeVVtMKSHeRQ
20,Rocketing Data Science,UCUIBKDoSSwehuDK4jk1CjFQ,1770,156826,88,UUUIBKDoSSwehuDK4jk1CjFQ
21,Jabrils,UCQALLeQPoZdZC4JNUboVEUg,496000,26821567,164,UUQALLeQPoZdZC4JNUboVEUg
22,DataCamp,UC79Gv3mYp6zKiSwYemEik9A,154000,22742404,1515,UU79Gv3mYp6zKiSwYemEik9A
23,Data With Mo,UCDybamfye5An6p-j1t2YMsg,72500,2168536,65,UUDybamfye5An6p-j1t2YMsg
24,techTFQ,UCnz-ZXXER4jOvuED5trXfEA,251000,13174447,100,UUnz-ZXXER4jOvuED5trXfEA
25,luke barousse,UCaGe6wVIAymH17HKO8kjQsw,346,3830,9,UUaGe6wVIAymH17HKO8kjQsw
26,Darshil Parmar,UCChmJrVa8kDg05JfCmxpLRw,102000,4183086,137,UUChmJrVa8kDg05JfCmxpLRw
27,Data Professor,UCV8e2g4IWQqK71bbzGDEI4Q,169000,5396263,323,UUV8e2g4IWQqK71bbzGDEI4Q
28,Alex The Analyst,UC7cs8q-gJRlGwj4A8OmCmXg,632000,26748451,262,UU7cs8q-gJRlGwj4A8OmCmXg
29,Andy McDonald,UCn1O_4_ApzbYwrsUdRoMmOg,6480,292040,47,UUn1O_4_ApzbYwrsUdRoMmOg
30,Thu Vu data analytics,UCJQJAI7IjbLcpsjWdSzYz0Q,174000,5813597,78,UUJQJAI7IjbLcpsjWdSzYz0Q
31,Learn with Lukas,UCw_LFe2pS8x3NyipGNJgeEA,27400,1455584,54,UUw_LFe2pS8x3NyipGNJgeEA
32,Krish Naik,UCNU_lfiiWBdtULKOw6X0Dig,841000,85088123,1745,UUNU_lfiiWBdtULKOw6X0Dig
33,Tom Henry - data science with R,UCb5aI-GwJm3ZxlwtCsLu78Q,3760,191418,16,UUb5aI-GwJm3ZxlwtCsLu78Q
34,Greg Hogg,UCJublDh2UsiIKsAE1553miw,55800,3430379,544,UUJublDh2UsiIKsAE1553miw
35,Data36 - Online Data Science Courses,UC9LfrPNcIyHspci0t2W4T_w,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w

# Get Video IDs

#### Procuring Playlist IDs for each Channel

In [9]:
playlist_id_list = list(channel_stats_df['playlist_id'])

## Function for Video IDs

In [10]:
def mass_video_ids(youtube, wanted_playlist_ids):

    all_data = []

    for id in wanted_playlist_ids:
        
        nextpage = True
        page = None

        while nextpage:
        # request for first page of playlist
            request = youtube.playlistItems().list(
                part='contentDetails',
                playlistId = id,
                maxResults=50,
                pageToken=page)
            # dictionary of the first page   
            response = request.execute()

        # Accessing videos ids on that first page
            for i in range(len(response['items'])):
                data = dict(playlist_id = id,
                    video_id = response['items'][i]['contentDetails']['videoId'])
                all_data.append(data)

            # Checking to see if there is a next page
            if 'nextPageToken' in response:
                page = response['nextPageToken']              

            else:
                nextpage = False
    # 
    all_data_df = pd.DataFrame(all_data)

    return all_data_df

## Video IDs Dataframe

In [11]:
channel_video_df = mass_video_ids(youtube, playlist_id_list)
channel_video_df.head()

                playlist_id     video_id
0  UU1emV4A8liRs9p80CY8ElUQ  v8Evfd6AFpw
1  UU1emV4A8liRs9p80CY8ElUQ  drXkf_rytRs
2  UU1emV4A8liRs9p80CY8ElUQ  yKi9-BfbfzQ
3  UU1emV4A8liRs9p80CY8ElUQ  koiPxFFiqJ4
4  UU1emV4A8liRs9p80CY8ElUQ  mBYSUUnMt9M

#### Checking Shape

In [12]:
channel_video_df.shape

(10768, 2)

#### Saving Dataframe

In [13]:
channel_stats_df.to_csv('channel_stats', index=False)

# What do we want from each video?

In [14]:
# Title (for NLP)
# Views
# Likes
# Tags
# Description
['id', 'publishedAt', 'channelId', 'title', 'description', 'tags', 'categoryId',
'defaultLanguage', 'duration', 'caption', 'licensedContent', 'contentRating',
'viewCount', 'likeCount', 'favoriteCount', 'commentCount']

['id',
 'publishedAt',
 'channelId',
 'title',
 'description',
 'tags',
 'categoryId',
 'defaultLanguage',
 'duration',
 'caption',
 'licensedContent',
 'contentRating',
 'viewCount',
 'likeCount',
 'favoriteCount',
 'commentCount']

# Function for Video Stats

#### Test Request

In [15]:
request = youtube.videos().list(
        part="snippet,contentDetails,statistics",
        id="L5Cis5bOwgw")
response = request.execute()
response

{'kind': 'youtube#videoListResponse',
 'etag': 'SROSHiNTeoIBCkLTCBcvR-RKu7A',
 'items': [{'kind': 'youtube#video',
   'etag': 'i2ANaY46bVYVy77GRW7-Ytz7cO0',
   'id': 'L5Cis5bOwgw',
   'snippet': {'publishedAt': '2023-11-17T12:00:28Z',
    'channelId': 'UCiT9RITQ9PW6BhXK0y2jaeg',
    'title': 'A Data Dream Come True',
    'description': '#datascience  #KenJee \nI gave up on my dream of playing professional golf 10 years ago. Recently, I had the opportunity to relive this through my data science and content work. Through this video, I also had the ability to reflect on how Data and AI are transforming golf while keeping the spirit of the game alive.  Special thanks to SAS for making this possible! \n\nSponsors, Affiliates, and Partners:\n- Pathrise - http://pathrise.com/KenJee | Career mentorship for job applicants (Free till you land a job)\n- Taro - http://jointaro.com/r/kenj308 (20% discount) | Career mentorship if you already have a job \n- 365 Data Science (57% discount) - https://365datascience.pxf.io/P0jbBY | Learn data science today\n- Interview Query (10% discount) - https://www.interviewquery.com/?ref=kenjee |  Interview prep questions\n\nMORE DATA SCIENCE CONTENT HERE:\nüê§My Twitter - https://twitter.com/KenJee_DS\nüëî LinkedIn -  https://www.linkedin.com/in/kenjee/\nüìà Kaggle - https://www.kaggle.com/kenjee\nüìë Medium Articles - https://medium.com/@kenneth.b.jee\nüíª Github - https://github.com/PlayingNumbers\nüèÄ My Sports Blog -https://www.playingnumbers.com\n\nCheck These Videos Out Next! \nMy Leaderboard Project: https://www.youtube.com/watch?v=myhoWUrSP7o&ab_channel=KenJee\n66 Days of Data: https://www.youtube.com/watch?v=qV_AlRwhI3I&ab_channel=KenJee\nHow I Would Learn Data Science in 2021: https://www.youtube.com/watch?v=41Clrh6nv1s&ab_channel=KenJee\n\nMy Playlists \nData Science Beginners: https://www.youtube.com/playlist?list=PL2zq7klxX5ATMsmyRazei7ZXkP1GHt-vs\nProject From Scratch: https://www.youtube.com/watch?v=MpF9HENQjDo&list=PL2zq7klxX5ASFejJj80ob9ZAnBHdz5O1t&ab_channel=KenJee\nKaggle Projects: https://www.youtube.com/playlist?list=PL2zq7klxX5AQXzNSLtc_LEKFPh2mAvHIO',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/L5Cis5bOwgw/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/L5Cis5bOwgw/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/L5Cis5bOwgw/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/L5Cis5bOwgw/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/L5Cis5bOwgw/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'Ken Jee',
    'tags': ['Data Science',
     'Ken Jee',
     'Machine Learning',
     'Sports Analytics',
     'data scientist',
     'data science journey',
     'data science 2023'],
    'categoryId': '28',
    'liveBroadcastContent': 'none',
    'defaultLanguage': 'en',
    'localized': {'title': 'A Data Dream Come True',
     'description': '#datascience  #KenJee \nI gave up on my dream of playing professional golf 10 years ago. Recently, I had the opportunity to relive this through my data science and content work. Through this video, I also had the ability to reflect on how Data and AI are transforming golf while keeping the spirit of the game alive.  Special thanks to SAS for making this possible! \n\nSponsors, Affiliates, and Partners:\n- Pathrise - http://pathrise.com/KenJee | Career mentorship for job applicants (Free till you land a job)\n- Taro - http://jointaro.com/r/kenj308 (20% discount) | Career mentorship if you already have a job \n- 365 Data Science (57% discount) - https://365datascience.pxf.io/P0jbBY | Learn data science today\n- Interview Query (10% discount) - https://www.interviewquery.com/?ref=kenjee |  Interview prep questions\n\nMORE DATA SCIENCE CONTENT HERE:\nüê§My Twitter - https://twitter.com/KenJee_DS\nüëî LinkedIn -  https://www.linkedin.com/in/kenjee/\nüìà Kaggle - https://www.kaggle.com/kenjee\nüìë Medium Articles - https://medium.com/@kenneth.b.jee\nüíª Github - https://github.com/PlayingNumbers\nüèÄ My Sports Blog -https://www.playingnumbers.com\n\nCheck These Videos Out Next! \nMy Leaderboard Project: https://www.youtube.com/watch?v=myhoWUrSP7o&ab_channel=KenJee\n66 Days of Data: https://www.youtube.com/watch?v=qV_AlRwhI3I&ab_channel=KenJee\nHow I Would Learn Data Science in 2021: https://www.youtube.com/watch?v=41Clrh6nv1s&ab_channel=KenJee\n\nMy Playlists \nData Science Beginners: https://www.youtube.com/playlist?list=PL2zq7klxX5ATMsmyRazei7ZXkP1GHt-vs\nProject From Scratch: https://www.youtube.com/watch?v=MpF9HENQjDo&list=PL2zq7klxX5ASFejJj80ob9ZAnBHdz5O1t&ab_channel=KenJee\nKaggle Projects: https://www.youtube.com/playlist?list=PL2zq7klxX5AQXzNSLtc_LEKFPh2mAvHIO'},
    'defaultAudioLanguage': 'en-US'},
   'contentDetails': {'duration': 'PT12M38S',
    'dimension': '2d',
    'definition': 'hd',
    'caption': 'false',
    'licensedContent': True,
    'contentRating': {},
    'projection': 'rectangular'},
   'statistics': {'viewCount': '1493',
    'likeCount': '74',
    'favoriteCount': '0',
    'commentCount': '22'}}],
 'pageInfo': {'totalResults': 1, 'resultsPerPage': 1}}

#### Finalised desired data pieces

In [16]:
['id', 'publishedAt', 'channelId', 'title', 'description', 'tags', 'categoryId',
'defaultLanguage', 'duration', 'caption', 'licensedContent', 'contentRating',
'viewCount', 'likeCount', 'favoriteCount', 'commentCount']

['id',
 'publishedAt',
 'channelId',
 'title',
 'description',
 'tags',
 'categoryId',
 'defaultLanguage',
 'duration',
 'caption',
 'licensedContent',
 'contentRating',
 'viewCount',
 'likeCount',
 'favoriteCount',
 'commentCount']

#### Testing Data Set of Video IDs

In [17]:
test_video_id_list = list(channel_video_df['video_id'])[:500]
print(len(test_video_id_list))
print(type(test_video_id_list))

500
<class 'list'>

#### Testing Results of Larger Requests

In [18]:
# request = youtube.videos().list(
#         part="snippet,contentDetails,statistics",
#         id=','.join(test_video_id_list))
# response = request.execute()
# response

HttpError: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/videos returned "The request specifies an invalid filter parameter.". Details: "[{'message': 'The request specifies an invalid filter parameter.', 'domain': 'youtube.parameter', 'reason': 'invalidFilters', 'location': 'parameters.', 'locationType': 'other'}]">

## Final Video Stats Function

In [27]:
def get_video_stats(youtube, list_of_video_ids):

    all_data = []

    # Will only return 50 results at a time, this for loop will do 50 Video IDs at a time
    for i in range(0, len(list_of_video_ids), 50):     

        request = youtube.videos().list(
            part="snippet,contentDetails,statistics",
            id=','.join(list_of_video_ids[i:i+50]))

        response = request.execute()

        for video in response['items']:
  
            data = dict(channel_id = video['snippet']['channelId'],
                        video_id = video['id'],
                        published_at = video['snippet'].get('publishedAt'),
                        title = video['snippet'].get('title'),
                        description = video['snippet'].get('description'),
                        tags = video['snippet'].get('tags', []), # was issue here as not all videos had tags, .get() might generally offer better protection
                        category_id = video['snippet'].get('categoryId'),
                        duration = video['contentDetails'].get('duration'),
                        caption = video['contentDetails'].get('caption'),
                        licensed_content = video['contentDetails'].get('licensedContent'),
                        content_rating = video['contentDetails'].get('contentRating'),
                        view_count = video['statistics'].get('viewCount'),
                        like_count = video['statistics'].get('likeCount'), # issue 
                        favourite_count = video['statistics'].get('favoriteCount'),
                        comment_count = video['statistics'].get('commentCount'))

            all_data.append(data)

    return all_data

In [22]:
video_stats = get_video_stats(youtube, test_video_id_list)

## Test Video Stats Dataframe

In [ ]:
video_stats_df = pd.DataFrame(video_stats)
video_stats_df

,channel_id,video_id,published_at,title,description,tags,category_id,duration,caption,licensed_content,content_rating,view_count,like_count,favourite_count,comment_count
0,UCJQJAI7IjbLcpsjWdSzYz0Q,HKYULsQr_U0,2023-11-12T17:06:48Z,Should You Still Learn to Code in 2024? #codin...,@Thuvu5,"[data analytics, data science, python, data, t...",22,PT40S,false,True,{},5157,240,0,8
1,UCJQJAI7IjbLcpsjWdSzYz0Q,fhFz0JfGvfc,2023-11-11T16:03:56Z,I Created a Custom GPT for Data Science Nerds ...,Try out Data Dynamo üëâ https://chat.openai.com/...,"[data analytics, data science, python, data, t...",22,PT11M36S,false,True,{},76781,1179,0,71
2,UCJQJAI7IjbLcpsjWdSzYz0Q,lp6SfYCRGLM,2023-10-16T22:03:49Z,ü§Ø AI Is Taking Over Data Jobs: Here's What To ...,üìä Curious about studying data analytics?¬†üß≠¬†Try...,"[data analytics, data science, python, data, p...",22,PT11M33S,false,True,{},5699,355,0,30
3,UCJQJAI7IjbLcpsjWdSzYz0Q,uGynMyXCcg8,2023-10-09T22:02:40Z,üìö BEST AI Books to Read in 2023,Artificial Intelligence üëâ https://amzn.to/3tnh...,"[data analytics, data science, python, data, t...",22,PT59S,false,True,{},7119,714,0,9
4,UCJQJAI7IjbLcpsjWdSzYz0Q,EzVIkHQWnhc,2023-08-22T00:29:27Z,Doing Data Analysis on Sensitive Data (ft. Obl...,üèÜ Check out Antigranular competition & win cas...,"[data analytics, data science, python, data, t...",22,PT12M19S,false,True,{},5338,263,0,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,UC79Gv3mYp6zKiSwYemEik9A,jMXZT5jgudQ,2023-11-20T12:15:03Z,The Data Democratization Stack (with Lilac Sch...,Lilac Schoenbeck shares what to focus on when ...,[],24,PT4M45S,false,False,{},86,1,0,0
496,UC79Gv3mYp6zKiSwYemEik9A,Zav-V3xwUkY,2023-11-20T10:14:35Z,#164 Driving Data Democratization with Lilac S...,The consequences of data not being easily acce...,[],24,PT48M46S,false,False,{},83,1,0,0
497,UC79Gv3mYp6zKiSwYemEik9A,Pb_RGAl75VE,2023-11-18T05:30:59Z,Fine-Tuning Your Own Llama 2 Model,The advent of large language models has taken ...,[],24,PT1H22M46S,false,False,{},681,36,0,0
498,UC79Gv3mYp6zKiSwYemEik9A,SmSoTa5eRZA,2023-11-17T05:14:06Z,Revolutionizing Decision Making using AI,"An average adult makes 35,000 decisions in a d...",[],24,PT1H8M22S,false,False,{},454,23,0,0
499,UC79Gv3mYp6zKiSwYemEik9A,SxJqyatlmTs,2023-11-16T05:06:43Z,"GPT-4 Turbo, Custom GPTs & the Assistants API","At OpenAI Dev Day, OpenAI announced a host of ...",[],24,PT1H2M16S,false,False,{},1117,40,0,0

In [23]:
len(video_stats)

500

# Full Video Database

#### Tasks

- Get full Database
- Combine with channel stats
- Duration mapping
- Category mapping
- Published date format
- Like Ratio new column?
- Tags format OHE?
- Has Tags/Doesn't have tags column
- Description word count
- Title word count

In [24]:
video_id_list = list(channel_video_df['video_id'])
print(len(video_id_list))
print(type(video_id_list))

10768
<class 'list'>

In [28]:
full_video_stats = get_video_stats(youtube, video_id_list)
full_video_stats_df = pd.DataFrame(full_video_stats)
full_video_stats_df

,channel_id,video_id,published_at,title,description,tags,category_id,duration,caption,licensed_content,content_rating,view_count,like_count,favourite_count,comment_count
0,UC1emV4A8liRs9p80CY8ElUQ,v8Evfd6AFpw,2023-11-08T12:25:45Z,Curso de JavaScript desde Cero - Aprende JavaS...,En este curso aprender√°s JavaScript desde cero...,"[JavaScript, programaci√≥n, programar, c√≥digo, ...",27,PT2H26M13S,false,True,{},23592,1773,0,66
1,UC1emV4A8liRs9p80CY8ElUQ,drXkf_rytRs,2023-09-06T11:41:13Z,"Crea una Pok√©dex con HTML, CSS y JavaScript (P...","Practica tus habilidades de HTML, CSS y JavaSc...","[freeCodeCamp, Pok√©dex, Pok√©mon, HTML, CSS, Ja...",27,PT1H2M10S,false,True,{},24518,1468,0,47
2,UC1emV4A8liRs9p80CY8ElUQ,yKi9-BfbfzQ,2023-08-15T12:13:02Z,Web Scraping con Python - Curso con Beautiful ...,Aprende a realizar web scraping con Python con...,"[Python, Web Scraping, Beautiful Soup, freeCod...",27,PT1H40M20S,false,True,{},40903,2143,0,106
3,UC1emV4A8liRs9p80CY8ElUQ,koiPxFFiqJ4,2023-06-19T11:30:19Z,JavaScript para Manipulaci√≥n del DOM - Curso c...,En este curso aprender√°s a usar JavaScript par...,"[JavaScript, freeCodeCamp, Desarrollo Web, DOM...",27,PT5H30M17S,false,True,{},103064,3949,0,253
4,UC1emV4A8liRs9p80CY8ElUQ,mBYSUUnMt9M,2023-02-09T13:52:39Z,Aprende Git y GitHub - Curso desde Cero,Aprende los fundamentos de Git y GitHub paso a...,"[Git, GitHub, programaci√≥n, programar, aprende...",27,PT5H32M55S,false,True,{},185975,7658,0,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10763,UC9LfrPNcIyHspci0t2W4T_w,lys6-be36f8,2017-07-18T20:54:43Z,0101 WELCOME TO THE COURSE | Data Science and ...,This video is part of my video course at O'Rei...,"[online data analysis, data science, data scie...",28,PT1M11S,true,False,{},478,2,0,0
10764,UC9LfrPNcIyHspci0t2W4T_w,DGtJAJUIxXw,2017-06-04T12:45:04Z,How to import a 7M+ rows data set into Postgre...,Continue with my SQL tutorial vids: https://ww...,"[online data analysis, data science, data scie...",28,PT6M18S,false,False,{},32217,234,0,30
10765,UC9LfrPNcIyHspci0t2W4T_w,WcZqmu9CdXk,2017-03-23T00:29:16Z,Data + Coding in Bash - episode 4 - Best Pract...,My Website: https://data36.com\nNewsletter: ht...,"[online data analysis, data science, data scie...",28,PT13M18S,false,False,{},5878,52,0,1
10766,UC9LfrPNcIyHspci0t2W4T_w,1vBbTD4xJ1Y,2017-03-16T16:02:30Z,Conversion Rate Optimization Framework ||| Tom...,Hey Folks! This is my first presentation about...,"[online data analysis, data science, data scie...",28,PT40M12S,true,False,{},2851,17,0,4
10767,UC9LfrPNcIyHspci0t2W4T_w,_GedQybWp2k,2017-02-08T13:14:04Z,Print a data file in Bash with Cat,This is a demo for the article published on da...,"[bash, data science, data science tutorial, da...",22,PT13S,false,False,{},1310,2,0,1

# Full Complete Database

In [30]:
full_df = full_video_stats_df.join(channel_stats_df, on='channel_id')
full_df

ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat

In [33]:
full_df = pd.merge(full_video_stats_df, channel_stats_df, on='channel_id', how='left')
full_df.tail()

,channel_id,video_id,published_at,title,description,tags,category_id,duration,caption,licensed_content,content_rating,view_count,like_count,favourite_count,comment_count,channel_name,subscribers,total_views,total_videos,playlist_id
10763,UC9LfrPNcIyHspci0t2W4T_w,lys6-be36f8,2017-07-18T20:54:43Z,0101 WELCOME TO THE COURSE | Data Science and ...,This video is part of my video course at O'Rei...,"[online data analysis, data science, data scie...",28,PT1M11S,true,False,{},478,2,0,0,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w
10764,UC9LfrPNcIyHspci0t2W4T_w,DGtJAJUIxXw,2017-06-04T12:45:04Z,How to import a 7M+ rows data set into Postgre...,Continue with my SQL tutorial vids: https://ww...,"[online data analysis, data science, data scie...",28,PT6M18S,false,False,{},32217,234,0,30,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w
10765,UC9LfrPNcIyHspci0t2W4T_w,WcZqmu9CdXk,2017-03-23T00:29:16Z,Data + Coding in Bash - episode 4 - Best Pract...,My Website: https://data36.com\nNewsletter: ht...,"[online data analysis, data science, data scie...",28,PT13M18S,false,False,{},5878,52,0,1,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w
10766,UC9LfrPNcIyHspci0t2W4T_w,1vBbTD4xJ1Y,2017-03-16T16:02:30Z,Conversion Rate Optimization Framework ||| Tom...,Hey Folks! This is my first presentation about...,"[online data analysis, data science, data scie...",28,PT40M12S,true,False,{},2851,17,0,4,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w
10767,UC9LfrPNcIyHspci0t2W4T_w,_GedQybWp2k,2017-02-08T13:14:04Z,Print a data file in Bash with Cat,This is a demo for the article published on da...,"[bash, data science, data science tutorial, da...",22,PT13S,false,False,{},1310,2,0,1,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w

In [34]:
full_df.to_csv('full_df', index=False)

# Youtube Categories

In [35]:
request = youtube.videoCategories().list(
        part="snippet",
        id="22")
response = request.execute()
response

{'kind': 'youtube#videoCategoryListResponse',
 'etag': 'fjjURLufs-ZQ351B8xY7itlOqtA',
 'items': [{'kind': 'youtube#videoCategory',
   'etag': 'cHDaaqPDZsJT1FPr1-MwtyIhR28',
   'id': '22',
   'snippet': {'title': 'People & Blogs',
    'assignable': True,
    'channelId': 'UCBR8-60-B28hp2BmDPdntcQ'}}]}

In [37]:
category_ids = full_df['category_id'].unique()
print(len(category_ids))

12

In [38]:
def get_categories(youtube, wanted_categories):

    all_data = []
    
    request = youtube.videoCategories().list(part='snippet', id=','.join(category_ids))
    
    response = request.execute()
    
    for i in range(len(response['items'])):
        data = dict(category_id = response['items'][i]['id'],
                category= response['items'][i]['snippet']['title'])
        all_data.append(data)

    return all_data

In [39]:
category_dict = get_categories(youtube, category_ids)
print(category_dict)

[{'category_id': '1', 'category': 'Film & Animation'}, {'category_id': '2', 'category': 'Autos & Vehicles'}, {'category_id': '10', 'category': 'Music'}, {'category_id': '17', 'category': 'Sports'}, {'category_id': '19', 'category': 'Travel & Events'}, {'category_id': '20', 'category': 'Gaming'}, {'category_id': '22', 'category': 'People & Blogs'}, {'category_id': '23', 'category': 'Comedy'}, {'category_id': '24', 'category': 'Entertainment'}, {'category_id': '26', 'category': 'Howto & Style'}, {'category_id': '27', 'category': 'Education'}, {'category_id': '28', 'category': 'Science & Technology'}]

In [40]:
category_df = pd.DataFrame(category_dict)
category_df

   category_id              category
0            1      Film & Animation
1            2      Autos & Vehicles
2           10                 Music
3           17                Sports
4           19       Travel & Events
5           20                Gaming
6           22        People & Blogs
7           23                Comedy
8           24         Entertainment
9           26         Howto & Style
10          27             Education
11          28  Science & Technology

In [42]:
full_df_v2 = pd.merge(full_df, category_df, on='category_id', how='left')
full_df_v2

,channel_id,video_id,published_at,title,description,tags,category_id,duration,caption,licensed_content,...,view_count,like_count,favourite_count,comment_count,channel_name,subscribers,total_views,total_videos,playlist_id,category
0,UC1emV4A8liRs9p80CY8ElUQ,v8Evfd6AFpw,2023-11-08T12:25:45Z,Curso de JavaScript desde Cero - Aprende JavaS...,En este curso aprender√°s JavaScript desde cero...,"[JavaScript, programaci√≥n, programar, c√≥digo, ...",27,PT2H26M13S,false,True,...,23592,1773,0,66,freeCodeCamp Espa√±ol,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ,Education
1,UC1emV4A8liRs9p80CY8ElUQ,drXkf_rytRs,2023-09-06T11:41:13Z,"Crea una Pok√©dex con HTML, CSS y JavaScript (P...","Practica tus habilidades de HTML, CSS y JavaSc...","[freeCodeCamp, Pok√©dex, Pok√©mon, HTML, CSS, Ja...",27,PT1H2M10S,false,True,...,24518,1468,0,47,freeCodeCamp Espa√±ol,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ,Education
2,UC1emV4A8liRs9p80CY8ElUQ,yKi9-BfbfzQ,2023-08-15T12:13:02Z,Web Scraping con Python - Curso con Beautiful ...,Aprende a realizar web scraping con Python con...,"[Python, Web Scraping, Beautiful Soup, freeCod...",27,PT1H40M20S,false,True,...,40903,2143,0,106,freeCodeCamp Espa√±ol,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ,Education
3,UC1emV4A8liRs9p80CY8ElUQ,koiPxFFiqJ4,2023-06-19T11:30:19Z,JavaScript para Manipulaci√≥n del DOM - Curso c...,En este curso aprender√°s a usar JavaScript par...,"[JavaScript, freeCodeCamp, Desarrollo Web, DOM...",27,PT5H30M17S,false,True,...,103064,3949,0,253,freeCodeCamp Espa√±ol,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ,Education
4,UC1emV4A8liRs9p80CY8ElUQ,mBYSUUnMt9M,2023-02-09T13:52:39Z,Aprende Git y GitHub - Curso desde Cero,Aprende los fundamentos de Git y GitHub paso a...,"[Git, GitHub, programaci√≥n, programar, aprende...",27,PT5H32M55S,false,True,...,185975,7658,0,495,freeCodeCamp Espa√±ol,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ,Education
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10763,UC9LfrPNcIyHspci0t2W4T_w,lys6-be36f8,2017-07-18T20:54:43Z,0101 WELCOME TO THE COURSE | Data Science and ...,This video is part of my video course at O'Rei...,"[online data analysis, data science, data scie...",28,PT1M11S,true,False,...,478,2,0,0,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w,Science & Technology
10764,UC9LfrPNcIyHspci0t2W4T_w,DGtJAJUIxXw,2017-06-04T12:45:04Z,How to import a 7M+ rows data set into Postgre...,Continue with my SQL tutorial vids: https://ww...,"[online data analysis, data science, data scie...",28,PT6M18S,false,False,...,32217,234,0,30,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w,Science & Technology
10765,UC9LfrPNcIyHspci0t2W4T_w,WcZqmu9CdXk,2017-03-23T00:29:16Z,Data + Coding in Bash - episode 4 - Best Pract...,My Website: https://data36.com\nNewsletter: ht...,"[online data analysis, data science, data scie...",28,PT13M18S,false,False,...,5878,52,0,1,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w,Science & Technology
10766,UC9LfrPNcIyHspci0t2W4T_w,1vBbTD4xJ1Y,2017-03-16T16:02:30Z,Conversion Rate Optimization Framework ||| Tom...,Hey Folks! This is my first presentation about...,"[online data analysis, data science, data scie...",28,PT40M12S,true,False,...,2851,17,0,4,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w,Science & Technology
10767,UC9LfrPNcIyHspci0t2W4T_w,_GedQybWp2k,2017-02-08T13:14:04Z,Print a data file in Bash with Cat,This is a demo for the article published on da...,"[bash, data science, data science tutorial, da...",22,PT13S,false,False,...,1310,2,0,1,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w,People & Blogs

In [57]:
full_df_v2['caption'].unique()
full_df_v2['caption'].value_counts()

false    9589
true     1179
Name: caption, dtype: int64

In [58]:
full_df_v2['licensed_content'].unique()
full_df_v2['licensed_content'].value_counts()

True     5523
False    5245
Name: licensed_content, dtype: int64

In [48]:
full_df_v2.to_csv('full_df.csv', index=False)

In [49]:
full_df_v2.describe()

,channel_id,video_id,published_at,title,description,tags,category_id,duration,caption,licensed_content,...,view_count,like_count,favourite_count,comment_count,channel_name,subscribers,total_views,total_videos,playlist_id,category
count,10768,10768,10768,10768,10768,10768,10768,10768,10768,10768,...,10768,10757,10768,10670,10768,10768,10768,10768,10768,10768
unique,36,10768,10675,10402,9537,7518,12,3746,2,2,...,8093,2421,1,585,36,36,36,34,36,12
top,UCObs0kLIrDjX2LLSybqNaEA,v8Evfd6AFpw,2019-03-08T22:34:17Z,study with me LIVE (2 hours) #accountability üêà...,,[],27,PT59S,false,True,...,0,1,0,0,Great Learning,807000,62821553,1853,UUObs0kLIrDjX2LLSybqNaEA,Education
freq,1854,1,15,83,156,1624,6540,64,9589,5523,...,25,283,10768,1866,1854,1854,1854,1854,1854,6540

In [50]:
full_df_v2.columns

Index(['channel_id', 'video_id', 'published_at', 'title', 'description',
       'tags', 'category_id', 'duration', 'caption', 'licensed_content',
       'content_rating', 'view_count', 'like_count', 'favourite_count',
       'comment_count', 'channel_name', 'subscribers', 'total_views',
       'total_videos', 'playlist_id', 'category'],
      dtype='object')

In [53]:
full_df_v2['content_rating'].value_counts()

{}    10768
Name: content_rating, dtype: int64

In [56]:
print(full_df_v2['content_rating'].explode().unique())

[nan]

# Duration Cleaning

#### Removing 'PT' from duration column

In [63]:
full_df_v2['duration'] = full_df_v2['duration'].str.replace('PT', '')

#### Conversion Function

In [64]:
from datetime import timedelta

# create function to format duration column
def format_duration(time_string):

    # store hours, minutes, seconds as integers
    H = 0
    M = 0
    S = 0

    # check if vid time contains hours, minutes and/or seconds
    if 'H' in time_string:
        H += int(time_string.split('H')[0])
    if 'M' in time_string:
        M += int(time_string.split('M')[0].split('H')[-1])
    if 'S' in time_string:
        S += int(time_string.split('S')[0].split('M')[-1].split('H')[-1])
    
    formatted_time = timedelta(hours=H, minutes=M, seconds=S)

    return formatted_time

In [65]:
full_df_v2['duration_formatted'] = full_df_v2['duration'].apply(format_duration)
full_df_v2

,channel_id,video_id,published_at,title,description,tags,category_id,duration,caption,licensed_content,...,like_count,favourite_count,comment_count,channel_name,subscribers,total_views,total_videos,playlist_id,category,duration_formatted
0,UC1emV4A8liRs9p80CY8ElUQ,v8Evfd6AFpw,2023-11-08T12:25:45Z,Curso de JavaScript desde Cero - Aprende JavaS...,En este curso aprender√°s JavaScript desde cero...,"[JavaScript, programaci√≥n, programar, c√≥digo, ...",27,2H26M13S,false,True,...,1773,0,66,freeCodeCamp Espa√±ol,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ,Education,0 days 02:26:13
1,UC1emV4A8liRs9p80CY8ElUQ,drXkf_rytRs,2023-09-06T11:41:13Z,"Crea una Pok√©dex con HTML, CSS y JavaScript (P...","Practica tus habilidades de HTML, CSS y JavaSc...","[freeCodeCamp, Pok√©dex, Pok√©mon, HTML, CSS, Ja...",27,1H2M10S,false,True,...,1468,0,47,freeCodeCamp Espa√±ol,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ,Education,0 days 01:02:10
2,UC1emV4A8liRs9p80CY8ElUQ,yKi9-BfbfzQ,2023-08-15T12:13:02Z,Web Scraping con Python - Curso con Beautiful ...,Aprende a realizar web scraping con Python con...,"[Python, Web Scraping, Beautiful Soup, freeCod...",27,1H40M20S,false,True,...,2143,0,106,freeCodeCamp Espa√±ol,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ,Education,0 days 01:40:20
3,UC1emV4A8liRs9p80CY8ElUQ,koiPxFFiqJ4,2023-06-19T11:30:19Z,JavaScript para Manipulaci√≥n del DOM - Curso c...,En este curso aprender√°s a usar JavaScript par...,"[JavaScript, freeCodeCamp, Desarrollo Web, DOM...",27,5H30M17S,false,True,...,3949,0,253,freeCodeCamp Espa√±ol,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ,Education,0 days 05:30:17
4,UC1emV4A8liRs9p80CY8ElUQ,mBYSUUnMt9M,2023-02-09T13:52:39Z,Aprende Git y GitHub - Curso desde Cero,Aprende los fundamentos de Git y GitHub paso a...,"[Git, GitHub, programaci√≥n, programar, aprende...",27,5H32M55S,false,True,...,7658,0,495,freeCodeCamp Espa√±ol,225000,7700004,78,UU1emV4A8liRs9p80CY8ElUQ,Education,0 days 05:32:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10763,UC9LfrPNcIyHspci0t2W4T_w,lys6-be36f8,2017-07-18T20:54:43Z,0101 WELCOME TO THE COURSE | Data Science and ...,This video is part of my video course at O'Rei...,"[online data analysis, data science, data scie...",28,1M11S,true,False,...,2,0,0,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w,Science & Technology,0 days 00:01:11
10764,UC9LfrPNcIyHspci0t2W4T_w,DGtJAJUIxXw,2017-06-04T12:45:04Z,How to import a 7M+ rows data set into Postgre...,Continue with my SQL tutorial vids: https://ww...,"[online data analysis, data science, data scie...",28,6M18S,false,False,...,234,0,30,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w,Science & Technology,0 days 00:06:18
10765,UC9LfrPNcIyHspci0t2W4T_w,WcZqmu9CdXk,2017-03-23T00:29:16Z,Data + Coding in Bash - episode 4 - Best Pract...,My Website: https://data36.com\nNewsletter: ht...,"[online data analysis, data science, data scie...",28,13M18S,false,False,...,52,0,1,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w,Science & Technology,0 days 00:13:18
10766,UC9LfrPNcIyHspci0t2W4T_w,1vBbTD4xJ1Y,2017-03-16T16:02:30Z,Conversion Rate Optimization Framework ||| Tom...,Hey Folks! This is my first presentation about...,"[online data analysis, data science, data scie...",28,40M12S,true,False,...,17,0,4,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w,Science & Technology,0 days 00:40:12
10767,UC9LfrPNcIyHspci0t2W4T_w,_GedQybWp2k,2017-02-08T13:14:04Z,Print a data file in Bash with Cat,This is a demo for the article published on da...,"[bash, data science, data science tutorial, da...",22,13S,false,False,...,2,0,1,Data36 - Online Data Science Courses,4810,204404,69,UU9LfrPNcIyHspci0t2W4T_w,People & Blogs,0 days 00:00:13