# Importing Libraries

In [3]:
from googleapiclient.discovery import build
import pandas as pd

# API Key

In [4]:
# api key AIzaSyBAobEQD70yA3gEWGjeZxGfyvvlwvMDsr8

# YouTube Connection

In [5]:
api_key = 'AIzaSyBAobEQD70yA3gEWGjeZxGfyvvlwvMDsr8'

youtube = build('youtube', 'v3', developerKey=api_key)

# Data Science Channel IDs

In [66]:
channel_ids = ['UCEBpSZhI1X8WaP-kY_2LLcg',
               'UCiT9RITQ9PW6BhXK0y2jaeg',
               'UCzL_0nIe8B4-7ShhVPfJkgw',
               'UC79Gv3mYp6zKiSwYemEik9A',
               'UCV8e2g4IWQqK71bbzGDEI4Q',
               'UCtYLUTtgS3k1Fg4y5tAhLbw',
               'UC7cs8q-gJRlGwj4A8OmCmXg',
               'UCiT9RITQ9PW6BhXK0y2jaeg',
               'UCnz-ZXXER4jOvuED5trXfEA',
               'UCteRPiisgIoHtMgqHegpWAQ',
               'UCSMqVwPTmerMiCaL_zKRjBw',
               'UCJublDh2UsiIKsAE1553miw',
               'UCvZnwzmc3m1Eush-Or8Z6DA',
               'UCNU_lfiiWBdtULKOw6X0Dig',
               'UCRqCK8izkO5xeVVtMKSHeRQ',
               'UC9LfrPNcIyHspci0t2W4T_w',
               'UCJQJAI7IjbLcpsjWdSzYz0Q',
               'UCaGe6wVIAymH17HKO8kjQsw',
               'UCWzIuRTyadYzg1-6OCejRMg',
               'UCHXa4OpASJEwrHrLeIzw7Yg',
               'UCb5aI-GwJm3ZxlwtCsLu78Q',
               'UCHGw1uT1XmqaRm-6W15-KlQ',
               'UCmMGlb7mGXYVthrXYSwlQhw',
               'UCSATlCAUi7R0Ik-wsZb2gOA',
               'UCDybamfye5An6p-j1t2YMsg',
               'UCVhQ2NnY5Rskt6UjCUkJ_DA',
               'UCq6XkhO5SZ66N04IcPbqNcw',
               'UCn1O_4_ApzbYwrsUdRoMmOg',
               'UCUIBKDoSSwehuDK4jk1CjFQ',
               'UCw_LFe2pS8x3NyipGNJgeEA',
               'UCPvDKIsrjA_h3g5yZJwCIHA',
               'UCObs0kLIrDjX2LLSybqNaEA',
               'UCChmJrVa8kDg05JfCmxpLRw',
               'UCup-fnSNRaByeuXOWqfnykw',
               'UCI8JpGrDmtggrryhml8kFGw',
               'UCkRFwipiIqBTakN-mkZ-GcQ']

In [ ]:
UCkRFwipiIqBTakN-mkZ-GcQ

# Function to Gather Channel Stats

In [67]:
def get_channel_stats(youtube, channel_id):
    
    all_data = []
    
    request = youtube.channels().list(part='snippet,contentDetails,statistics', id=','.join(channel_ids))
    
    response = request.execute()
    
    for i in range(len(response['items'])):
        data = dict(channel_name = response['items'][i]['snippet']['title'],
                channel_id = response['items'][i]['id'],
                subscribers = response['items'][i]['statistics']['subscriberCount'],
                total_views = response['items'][i]['statistics']['viewCount'],
                total_videos = response['items'][i]['statistics']['videoCount'],
                playlist_id = response['items'][i]['contentDetails']['relatedPlaylists']['uploads'])
        all_data.append(data)
    
    return all_data

In [68]:
channel_stats = get_channel_stats(youtube, channel_ids)

In [85]:
request = youtube.channels().list(part='snippet,contentDetails,statistics', forUsername='TinaHueng1')
response = request.execute()
response

{'kind': 'youtube#channelListResponse',
 'etag': 'RuuXzTIr0OoDqI4S0RU6n4FqKEM',
 'pageInfo': {'totalResults': 0, 'resultsPerPage': 5}}

# Creating Dataframe

In [69]:
channel_stats_df = pd.DataFrame(channel_stats)
channel_stats_df

,channel_name,channel_id,subscribers,total_views,total_videos,playlist_id
0,Sundas Khalid,UCteRPiisgIoHtMgqHegpWAQ,182000,9172433,115,UUteRPiisgIoHtMgqHegpWAQ
1,Alex The Analyst,UC7cs8q-gJRlGwj4A8OmCmXg,636000,26970058,265,UU7cs8q-gJRlGwj4A8OmCmXg
2,Tech Classes,UCPvDKIsrjA_h3g5yZJwCIHA,29600,1912648,155,UUPvDKIsrjA_h3g5yZJwCIHA
3,Shashank Kalanithi,UCvZnwzmc3m1Eush-Or8Z6DA,139000,6514896,152,UUvZnwzmc3m1Eush-Or8Z6DA
4,Jon Krohn,UCup-fnSNRaByeuXOWqfnykw,18600,709161,143,UUup-fnSNRaByeuXOWqfnykw
5,StatQuest with Josh Starmer,UCtYLUTtgS3k1Fg4y5tAhLbw,1050000,56761048,265,UUtYLUTtgS3k1Fg4y5tAhLbw
6,Nicholas Renotte,UCHXa4OpASJEwrHrLeIzw7Yg,217000,13899123,303,UUHXa4OpASJEwrHrLeIzw7Yg
7,Rocketing Data Science,UCUIBKDoSSwehuDK4jk1CjFQ,1790,160294,88,UUUIBKDoSSwehuDK4jk1CjFQ
8,Data Science for High School,UCWzIuRTyadYzg1-6OCejRMg,32,1327,34,UUWzIuRTyadYzg1-6OCejRMg
9,Data Professor,UCV8e2g4IWQqK71bbzGDEI4Q,169000,5424566,323,UUV8e2g4IWQqK71bbzGDEI4Q
10,Joma in NYC,UCmMGlb7mGXYVthrXYSwlQhw,260000,14904178,20,UUmMGlb7mGXYVthrXYSwlQhw
11,Study with Tina,UCI8JpGrDmtggrryhml8kFGw,20900,290796,249,UUI8JpGrDmtggrryhml8kFGw
12,Data With Mo,UCDybamfye5An6p-j1t2YMsg,73400,2202886,66,UUDybamfye5An6p-j1t2YMsg
13,Dataiku,UCSMqVwPTmerMiCaL_zKRjBw,15100,9130117,684,UUSMqVwPTmerMiCaL_zKRjBw
14,techTFQ,UCnz-ZXXER4jOvuED5trXfEA,253000,13258296,100,UUnz-ZXXER4jOvuED5trXfEA
15,DataCamp,UC79Gv3mYp6zKiSwYemEik9A,154000,22767611,1521,UU79Gv3mYp6zKiSwYemEik9A
16,luke barousse,UCaGe6wVIAymH17HKO8kjQsw,367,4326,9,UUaGe6wVIAymH17HKO8kjQsw
17,Great Learning,UCObs0kLIrDjX2LLSybqNaEA,808000,62893376,1854,UUObs0kLIrDjX2LLSybqNaEA
18,Krish Naik,UCNU_lfiiWBdtULKOw6X0Dig,844000,85419946,1748,UUNU_lfiiWBdtULKOw6X0Dig
19,Keith Galli,UCq6XkhO5SZ66N04IcPbqNcw,208000,14243345,80,UUq6XkhO5SZ66N04IcPbqNcw
20,Data Nash,UCRqCK8izkO5xeVVtMKSHeRQ,18800,897316,50,UURqCK8izkO5xeVVtMKSHeRQ
21,Data Science Dojo,UCzL_0nIe8B4-7ShhVPfJkgw,101000,5714166,455,UUzL_0nIe8B4-7ShhVPfJkgw
22,Thu Vu data analytics,UCJQJAI7IjbLcpsjWdSzYz0Q,176000,5865940,79,UUJQJAI7IjbLcpsjWdSzYz0Q
23,Darshil Parmar,UCChmJrVa8kDg05JfCmxpLRw,103000,4245007,138,UUChmJrVa8kDg05JfCmxpLRw
24,365 Data Science,UCEBpSZhI1X8WaP-kY_2LLcg,302000,13364695,223,UUEBpSZhI1X8WaP-kY_2LLcg
25,Learn with Lukas,UCw_LFe2pS8x3NyipGNJgeEA,27900,1495722,55,UUw_LFe2pS8x3NyipGNJgeEA
26,Time Out With Tim,UCSATlCAUi7R0Ik-wsZb2gOA,6410,28454,9,UUSATlCAUi7R0Ik-wsZb2gOA
27,ArjanCodes,UCVhQ2NnY5Rskt6UjCUkJ_DA,207000,14204788,306,UUVhQ2NnY5Rskt6UjCUkJ_DA
28,Ken Jee,UCiT9RITQ9PW6BhXK0y2jaeg,254000,8716834,286,UUiT9RITQ9PW6BhXK0y2jaeg
29,Tom Henry - data science with R,UCb5aI-GwJm3ZxlwtCsLu78Q,3760,191810,16,UUb5aI-GwJm3ZxlwtCsLu78Q
30,Andy McDonald,UCn1O_4_ApzbYwrsUdRoMmOg,6550,296026,48,UUn1O_4_ApzbYwrsUdRoMmOg
31,Greg Hogg,UCJublDh2UsiIKsAE1553miw,56500,3530237,551,UUJublDh2UsiIKsAE1553miw
32,Data Science Basics,UCHGw1uT1XmqaRm-6W15-KlQ,5840,292716,149,UUHGw1uT1XmqaRm-6W15-KlQ
33,Data36 - Online Data Science Courses,UC9LfrPNcIyHspci0t2W4T_w,4810,204978,69,UU9LfrPNcIyHspci0t2W4T_w

In [ ]:
UCkRFwipiIqBTakN-mkZ-GcQ

In [70]:
channel_stats_df.dtypes

channel_name    object
channel_id      object
subscribers     object
total_views     object
total_videos    object
playlist_id     object
dtype: object

In [71]:
channel_stats_df[['subscribers', 'total_views', 'total_videos']] = channel_stats_df[['subscribers', 'total_views', 'total_videos']].astype(int)

# Choosing Channels Based on Size

In [72]:
channel_stats_df.describe().round(2)

       subscribers  total_views  total_videos
count        34.00        34.00         34.00
mean     186863.50  11932032.94        312.00
std      262492.79  19445874.96        469.37
min          32.00      1327.00          9.00
25%       15975.00    399309.75         66.75
50%      102000.00   5569366.00        146.00
75%      214750.00  13765516.00        298.75
max     1050000.00  85419946.00       1854.00

In [73]:
channel_stats_df.sort_values('subscribers', ascending=False)

,channel_name,channel_id,subscribers,total_views,total_videos,playlist_id
5,StatQuest with Josh Starmer,UCtYLUTtgS3k1Fg4y5tAhLbw,1050000,56761048,265,UUtYLUTtgS3k1Fg4y5tAhLbw
18,Krish Naik,UCNU_lfiiWBdtULKOw6X0Dig,844000,85419946,1748,UUNU_lfiiWBdtULKOw6X0Dig
17,Great Learning,UCObs0kLIrDjX2LLSybqNaEA,808000,62893376,1854,UUObs0kLIrDjX2LLSybqNaEA
1,Alex The Analyst,UC7cs8q-gJRlGwj4A8OmCmXg,636000,26970058,265,UU7cs8q-gJRlGwj4A8OmCmXg
24,365 Data Science,UCEBpSZhI1X8WaP-kY_2LLcg,302000,13364695,223,UUEBpSZhI1X8WaP-kY_2LLcg
10,Joma in NYC,UCmMGlb7mGXYVthrXYSwlQhw,260000,14904178,20,UUmMGlb7mGXYVthrXYSwlQhw
28,Ken Jee,UCiT9RITQ9PW6BhXK0y2jaeg,254000,8716834,286,UUiT9RITQ9PW6BhXK0y2jaeg
14,techTFQ,UCnz-ZXXER4jOvuED5trXfEA,253000,13258296,100,UUnz-ZXXER4jOvuED5trXfEA
6,Nicholas Renotte,UCHXa4OpASJEwrHrLeIzw7Yg,217000,13899123,303,UUHXa4OpASJEwrHrLeIzw7Yg
19,Keith Galli,UCq6XkhO5SZ66N04IcPbqNcw,208000,14243345,80,UUq6XkhO5SZ66N04IcPbqNcw
27,ArjanCodes,UCVhQ2NnY5Rskt6UjCUkJ_DA,207000,14204788,306,UUVhQ2NnY5Rskt6UjCUkJ_DA
0,Sundas Khalid,UCteRPiisgIoHtMgqHegpWAQ,182000,9172433,115,UUteRPiisgIoHtMgqHegpWAQ
22,Thu Vu data analytics,UCJQJAI7IjbLcpsjWdSzYz0Q,176000,5865940,79,UUJQJAI7IjbLcpsjWdSzYz0Q
9,Data Professor,UCV8e2g4IWQqK71bbzGDEI4Q,169000,5424566,323,UUV8e2g4IWQqK71bbzGDEI4Q
15,DataCamp,UC79Gv3mYp6zKiSwYemEik9A,154000,22767611,1521,UU79Gv3mYp6zKiSwYemEik9A
3,Shashank Kalanithi,UCvZnwzmc3m1Eush-Or8Z6DA,139000,6514896,152,UUvZnwzmc3m1Eush-Or8Z6DA
23,Darshil Parmar,UCChmJrVa8kDg05JfCmxpLRw,103000,4245007,138,UUChmJrVa8kDg05JfCmxpLRw
21,Data Science Dojo,UCzL_0nIe8B4-7ShhVPfJkgw,101000,5714166,455,UUzL_0nIe8B4-7ShhVPfJkgw
12,Data With Mo,UCDybamfye5An6p-j1t2YMsg,73400,2202886,66,UUDybamfye5An6p-j1t2YMsg
31,Greg Hogg,UCJublDh2UsiIKsAE1553miw,56500,3530237,551,UUJublDh2UsiIKsAE1553miw
2,Tech Classes,UCPvDKIsrjA_h3g5yZJwCIHA,29600,1912648,155,UUPvDKIsrjA_h3g5yZJwCIHA
25,Learn with Lukas,UCw_LFe2pS8x3NyipGNJgeEA,27900,1495722,55,UUw_LFe2pS8x3NyipGNJgeEA
11,Study with Tina,UCI8JpGrDmtggrryhml8kFGw,20900,290796,249,UUI8JpGrDmtggrryhml8kFGw
20,Data Nash,UCRqCK8izkO5xeVVtMKSHeRQ,18800,897316,50,UURqCK8izkO5xeVVtMKSHeRQ
4,Jon Krohn,UCup-fnSNRaByeuXOWqfnykw,18600,709161,143,UUup-fnSNRaByeuXOWqfnykw
13,Dataiku,UCSMqVwPTmerMiCaL_zKRjBw,15100,9130117,684,UUSMqVwPTmerMiCaL_zKRjBw
30,Andy McDonald,UCn1O_4_ApzbYwrsUdRoMmOg,6550,296026,48,UUn1O_4_ApzbYwrsUdRoMmOg
26,Time Out With Tim,UCSATlCAUi7R0Ik-wsZb2gOA,6410,28454,9,UUSATlCAUi7R0Ik-wsZb2gOA
32,Data Science Basics,UCHGw1uT1XmqaRm-6W15-KlQ,5840,292716,149,UUHGw1uT1XmqaRm-6W15-KlQ
33,Data36 - Online Data Science Courses,UC9LfrPNcIyHspci0t2W4T_w,4810,204978,69,UU9LfrPNcIyHspci0t2W4T_w
29,Tom Henry - data science with R,UCb5aI-GwJm3ZxlwtCsLu78Q,3760,191810,16,UUb5aI-GwJm3ZxlwtCsLu78Q
7,Rocketing Data Science,UCUIBKDoSSwehuDK4jk1CjFQ,1790,160294,88,UUUIBKDoSSwehuDK4jk1CjFQ
16,luke barousse,UCaGe6wVIAymH17HKO8kjQsw,367,4326,9,UUaGe6wVIAymH17HKO8kjQsw
8,Data Science for High School,UCWzIuRTyadYzg1-6OCejRMg,32,1327,34,UUWzIuRTyadYzg1-6OCejRMg

#### Only channels with over 20,000 subscribers and over 50 total videos

In [74]:
chosen_channels_df = channel_stats_df[(channel_stats_df.subscribers >= 20000) & (channel_stats_df.total_videos >= 50)].reset_index(drop=True)

In [75]:
chosen_channels_df

,channel_name,channel_id,subscribers,total_views,total_videos,playlist_id
0,Sundas Khalid,UCteRPiisgIoHtMgqHegpWAQ,182000,9172433,115,UUteRPiisgIoHtMgqHegpWAQ
1,Alex The Analyst,UC7cs8q-gJRlGwj4A8OmCmXg,636000,26970058,265,UU7cs8q-gJRlGwj4A8OmCmXg
2,Tech Classes,UCPvDKIsrjA_h3g5yZJwCIHA,29600,1912648,155,UUPvDKIsrjA_h3g5yZJwCIHA
3,Shashank Kalanithi,UCvZnwzmc3m1Eush-Or8Z6DA,139000,6514896,152,UUvZnwzmc3m1Eush-Or8Z6DA
4,StatQuest with Josh Starmer,UCtYLUTtgS3k1Fg4y5tAhLbw,1050000,56761048,265,UUtYLUTtgS3k1Fg4y5tAhLbw
5,Nicholas Renotte,UCHXa4OpASJEwrHrLeIzw7Yg,217000,13899123,303,UUHXa4OpASJEwrHrLeIzw7Yg
6,Data Professor,UCV8e2g4IWQqK71bbzGDEI4Q,169000,5424566,323,UUV8e2g4IWQqK71bbzGDEI4Q
7,Study with Tina,UCI8JpGrDmtggrryhml8kFGw,20900,290796,249,UUI8JpGrDmtggrryhml8kFGw
8,Data With Mo,UCDybamfye5An6p-j1t2YMsg,73400,2202886,66,UUDybamfye5An6p-j1t2YMsg
9,techTFQ,UCnz-ZXXER4jOvuED5trXfEA,253000,13258296,100,UUnz-ZXXER4jOvuED5trXfEA
10,DataCamp,UC79Gv3mYp6zKiSwYemEik9A,154000,22767611,1521,UU79Gv3mYp6zKiSwYemEik9A
11,Great Learning,UCObs0kLIrDjX2LLSybqNaEA,808000,62893376,1854,UUObs0kLIrDjX2LLSybqNaEA
12,Krish Naik,UCNU_lfiiWBdtULKOw6X0Dig,844000,85419946,1748,UUNU_lfiiWBdtULKOw6X0Dig
13,Keith Galli,UCq6XkhO5SZ66N04IcPbqNcw,208000,14243345,80,UUq6XkhO5SZ66N04IcPbqNcw
14,Data Science Dojo,UCzL_0nIe8B4-7ShhVPfJkgw,101000,5714166,455,UUzL_0nIe8B4-7ShhVPfJkgw
15,Thu Vu data analytics,UCJQJAI7IjbLcpsjWdSzYz0Q,176000,5865940,79,UUJQJAI7IjbLcpsjWdSzYz0Q
16,Darshil Parmar,UCChmJrVa8kDg05JfCmxpLRw,103000,4245007,138,UUChmJrVa8kDg05JfCmxpLRw
17,365 Data Science,UCEBpSZhI1X8WaP-kY_2LLcg,302000,13364695,223,UUEBpSZhI1X8WaP-kY_2LLcg
18,Learn with Lukas,UCw_LFe2pS8x3NyipGNJgeEA,27900,1495722,55,UUw_LFe2pS8x3NyipGNJgeEA
19,ArjanCodes,UCVhQ2NnY5Rskt6UjCUkJ_DA,207000,14204788,306,UUVhQ2NnY5Rskt6UjCUkJ_DA
20,Ken Jee,UCiT9RITQ9PW6BhXK0y2jaeg,254000,8716834,286,UUiT9RITQ9PW6BhXK0y2jaeg
21,Greg Hogg,UCJublDh2UsiIKsAE1553miw,56500,3530237,551,UUJublDh2UsiIKsAE1553miw